name: Main

on:
  pull_request:
  push:

jobs:
  check-format:
    name: Check - Format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> .npmrc

      - name: Build
        run: npm install --ignore-scripts

      - name: Prettier
        run: npm run format-check -- --color

  check-lint:
    name: Check - Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> .npmrc

      - name: Build
        run: npm install --ignore-scripts

      - name: ESLint
        run: npm run lint -- --color

  check-spelling:
    name: Check - Spelling

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> .npmrc

      - name: Build
        run: npm install --ignore-scripts

      - name: cSpell
        run: npm run spellcheck -- --color

  check-tests:
    name: Check - Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> .npmrc

      - name: Install Dependencies and Build
        run: npm install

      - name: Run Tests
        run: npm test -- --no-coverage

  check-direct-execute:
    name: Check - Direct Execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> .npmrc

      - name: Install Dependencies and Build
        run: npm install

      - name: Run dist/clone Manually
        run: node dist/clone
        env:
          INPUT_BRANCH: master
          INPUT_WORKING-DIRECTORY: /tmp/fake-clone
          INPUT_REPO: '.'

  bootstrap-coverage-reports:
    name: Self Test - Generate Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> .npmrc

      - name: Install Dependencies and Build
        run: npm install

      - name: ---- Files after build
        uses: cinderblock/github-action-debug-list-files@v1

        # Test with self
      - name: Use self as action to test and store historic coverage reports
        uses: dist
        # This step will copy coverage reports (and others) to the specified historical branch
        # and use it to generate some pretty charts
        with:
          branch: allure-results/${{ github.ref }}
          working-directory: allure-results

      - name: ---- Files after loading allure results
        uses: cinderblock/github-action-debug-list-files@v1

        # Run Tests
      - name: Run Tests
        run: npm test -- --color

      - name: ---- Files after coverage test
        uses: cinderblock/github-action-debug-list-files@v1

      - name: Generate Allure Report
        run: npm run finalize-coverage-reports

      - name: ---- Files after Allure gen
        uses: cinderblock/github-action-debug-list-files@v1

      # Publish to gh-pages
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public
        with:
          emptyCommits: false
          username: 'GitHub Action Static Build'
          #useremail: "actions@github.com"

  publish-v1:
    name: Publish - GitHub Action v1
    if: github.event_name == 'push' && github.ref == 'refs/heads/release'
    needs: [check-format, check-lint, check-spelling, check-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Configure Npm
        run: |
          echo "color = always" >> .npmrc

      - name: Install Dependencies and Build
        run: npm install

      - name: Publish to GitHub as v1
        uses: peaceiris/actions-gh-pages@v2
        env:
          PUBLISH_BRANCH: v1
          PUBLISH_DIR: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          emptyCommits: false
          username: 'GitHub Action Static Build'
          #useremail: "actions@github.com"

  test-published:
    name: Test - Published
    needs: [publish-v1]
    runs-on: ubuntu-latest
    steps:
      - name: Use latest published version # to make sure it can be used as expected
        uses: cinderblock/github-action-working-directory@v1
